name: xplore_bg_v2
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  auto_route: ^3.2.4
  bottom_bar: ^1.3.0+1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.13
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.0
  expand_widget: ^2.1.0
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.13
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^4.3.0
  flutter_hooks: ^0.18.2+1
  flutter_map: ^0.14.0
  flutter_rating_bar: ^4.0.0
  flutter_staggered_grid_view: ^0.6.1
  flutter_swipe_action_cell: ^2.2.0
  flutter_vector_icons: ^1.0.0
  freezed_annotation: ^2.0.1
  get: ^4.6.1
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.3
  google_sign_in: ^5.3.0
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  intl: ^0.17.0
  latlong2: ^0.8.1
  line_icons: ^2.0.1
  loading_indicator: ^3.0.3
  marquee: ^2.2.1
  meilisearch: ^0.5.1
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master
  rating_bar: ^0.2.0
  skeleton_text: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  sliver_tools: ^0.2.5
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/categories/
    - assets/images/maps/
    - assets/images/
    - .env
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
